### ISSUE TITLE
Source Name inaccurate

### ISSUE THREAD

**Issue by aarondcounts** [Graylog2/graylog2-stream-dashboard#13]
When I go to the Sources tab in Graylog to see my top sources, the names are showing as anything but the actual source. i.e.: jun; tcp; connection; udp; icmp; permitted; denied; etc. Can someone help me fix this? I would like for it to use the PTR for the IP sending the syslogs or if it cannot do that use the IP or hostname.

**Comment by joschi** [comment]
Is the `source` attribute correct if you check the messages in Graylog instead of the stream dashboard?

**Comment by dennisoelkers** [comment]
This is actually the wrong repository for an issue related to the web interface. Could you please reopen the issue [here](https://github.com/Graylog2/graylog2-web-interface/issues/new)? Thanks!

**Comment by joschi** [comment]
Ah, I see.

The question is probably better asked on the [mailing list](https://groups.google.com/forum/#!forum/graylog2) as it seems to be a problem with the syslog parser.
