### ISSUE TITLE
Create stream button doesnt appear

### ISSUE THREAD

**Issue by pierrick-openIT** [Graylog2/graylog2-stream-dashboard#15]
Hy guys,

i'm on Graylog 2.1.2+50e449a and when i click on stream menu, i have nothing to create a stream.

<img width="651" alt="capture" src="https://cloud.githubusercontent.com/assets/23313214/20424854/31506e0c-ad78-11e6-9e9e-af66d770d9e2.PNG">

Regards.

**Comment by joschi** [comment]
This issue was moved to Graylog2/graylog2-server#3099
